#!/usr/bin/env python3
import glob
import random
import sys

WALLPAPER_DIRECTORY = "/mnt/nfs1/Pictures/Wallpapers/"


args = sys.argv[1:]

if len(args) == 0:
    args = [""]

walls = list()

for source in args:
    walls += glob.glob(WALLPAPER_DIRECTORY + source + "/*.*")

print(random.choice(walls))
